services:
  service1: &service
    build:
      context: .
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - NODE_ENV=production
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "120MB"

  service2:
    <<: *service
    build:
      context: .
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - HEALTH_CHECK_ENABLED=1

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    ports:
    - 6379:6379
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "60MB"
    networks:
      - backend
  
  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - service1
      - service2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true


    